### ISSUE TITLE
List available services

### ISSUE THREAD

**Issue by ninsbl** [pesekon2/GRASS-GIS-SOS-tools#13]
Would it be possible to also list all available services on a server?

**Comment by pesekon2** [comment]
Sorry, but what do you mean by services on a server? Like urls for free services?

**Comment by ninsbl** [comment]
I was thinking about a flag (let say "-s" for "print available services"), that would return "edenext" (or all accessible services for an anonymous / specific user) for the
`v.in.sos -s url=http://istsos.geodati.fmach.it/istsos `
Since I do not have reasonable experience with data organisation on SOS server, I am not sure if e.g. data regularly is organized in different services on one server (meaning if such a flag would make sense). 
In the istSOS data management panel at least you can select from different services. But that is maybe specific for that implementation and not part of the OGC standard...
No idea if that is even theoretically possible to achieve via OWSlib.

**Comment by pesekon2** [comment]
I'm afraid that it's not possible via OWSLib, but I labeled it as enhancement and I will take a deeper look.

**Comment by lucadelu** [comment]
@ninsbl I don't think it is possible, the edenext service is something related to istSOS and not to SOS standard. It seems that the first service is also the name used in by istSOS for something like an internal proxy. Maybe we have to ask istsos guys..

**Comment by ninsbl** [comment]
The more I think about it, the less valid does my request feel. Most likely, one would not do that in case of other OWS and system administrators would not like it if it was possible...
Closing the issue, cause I don`t think it is worth spending even more time on it.
A proper service URL is a valid minimum requirement.
