### ISSUE TITLE
add shell script style output

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#16]
Please add also a shell script style output for the various print options `-o` , `-p`, `-t`. The common flag for this is `-g`

`-o` for this query `python t.vect.in.sos/t.vect.in.sos.py -o url=http://istsos.geodati.fmach.it/istsos/edenext?` should be

```
GRIDA
GRIDC
GRIDE
GRIDF
temporary
```
`-p` for this query `python t.vect.in.sos/t.vect.in.sos.py -p url=http://istsos.geodati.fmach.it/istsos/edenext? offering=GRIDA` should be

```
GRIDA_A1_HIGH
GRIDA_A1_LOW
......
GRIDA_H8_HIGH
GRIDA_H8_LOW
```

`-t` for this query `python t.vect.in.sos/t.vect.in.sos.py -t url=http://istsos.geodati.fmach.it/istsos/edenext? offering=GRIDA procedure=GRIDA_A1_HIGH` should be 
```
start_time=2012-03-14 18:28:01+01:00
end_time=2014-11-20 11:23:01+01:00
```
I have no clear idea about how to do that, probably could be useful to add this in OWSlib..

**Comment by pesekon2** [comment]
What do you think about [this commit](https://github.com/pesekon2/GRASS-GIS-SOS-tools/commit/11dcefd601a061f786ddcaf4cb1a11ee0c06a10b)?

**Comment by lucadelu** [comment]
It is good for the dates output, for the offerings and procedures you should remove ` urn:ogc:def:offering:x-istsos:1.0` and `urn:ogc:def:procedure:x-istsos:1.0`

I think it should be added to OWSlib... maybe ask to OWSlib mailing list

I had few comments in [commit](https://github.com/pesekon2/GRASS-GIS-SOS-tools/commit/11dcefd601a061f786ddcaf4cb1a11ee0c06a10b)
