### ISSUE TITLE
v.in.sos doesn't generate UI

### ISSUE THREAD

**Issue by pesekon2** [pesekon2/GRASS-GIS-SOS-tools#2]
When trying to run `python v.in.sos.py --ui` in GRASS, it ends with error message:

> Unable to fetch interface description for command '/home/ondrej/workspace/GRASS-GIS-SOS-tools/v.in.sos/v.in.sos.py'
> Try to set up GRASS_ADDON_PATH or GRASS_ADDON_BASE variable.

**Comment by lucadelu** [comment]
You need to compile the module to have the ui.

Please add Makefile and html file in v.in.sos folder, and after compile the module following [these instructions](https://grasswiki.osgeo.org/wiki/Compile_and_Install#Addons)
