### ISSUE TITLE
quiet vector creation

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#21]
In t.vect.in.sos if it is possible put quiet during creation of vector to not show all the vector creation.

If quiet flag doesn't exist/work I suggest to capture the standard output....

**Comment by pesekon2** [comment]
Those messages are created by v.new.close() because it's building topology. And there isn't anything like quiet output. The only thing I can do is set build_topology=False when we want quiet output, but is it standard way? Shouldn't it raise some problems?
