### ISSUE TITLE
get_observation returns only one coordinates

### ISSUE THREAD

**Issue by pesekon2** [pesekon2/GRASS-GIS-SOS-tools#24]
Command [1] returns the same coordinates for each procedure even if that procedures had originally different coordinates sometimes. Seems like a bug in OWSLib. 

[1] https://github.com/pesekon2/GRASS-GIS-SOS-tools/blob/master/v.in.sos/v.in.sos.py#L180

**Comment by pesekon2** [comment]
I have found why. It happens when those points have the same name of Location in metadata, because get_observation request takes the coordinates from <gml:location> and not from <om:procedure>. Mazbe it isn't an issue and it's a purpose, but it still seems like an issue to me (for example, there can be location Paris, but the sensors can be on different places inside Paris). @lucadelu should I write to istSOS authors, or to OWSLib?

**Comment by lucadelu** [comment]
@pesekon2 sorry for the delay, I have no idea is it is a feature or a bug, neither if is coming from istSOS or OWSLib, did you try with a different server?
