### ISSUE TITLE
v.in.sos cleanup temporary maps

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#27]
Running 

```
v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida_vector offering=GRIDA event_time='2012-03-14T18:28:01+01:00/2012-03-14T19:33:01+01:00' observed_properties=temperature,air:humidity:relative
```

I got more maps than the output (grida_vector), please remove all the temporary maps

```
g.list type=vector

grid0
grid3
grid30
grid_old
grida_vector
```

Only `grida_vector` should be there

**Comment by pesekon2** [comment]
It's really strange behaviour, I have never noticed something like that. Even when I try your command, I get
```
> g.list type=vector
grida_vector
```

**Comment by lucadelu** [comment]
Sorry the others grid are coming from permanent... closing this
