### ISSUE TITLE
granularity

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#32]
Some comments about granularity:
- [x] granularity should follow the same idea of temporal modules, so please don't use  granularity and granularity_units but only granularity, if you need there are useful functions in the [temporal library](https://trac.osgeo.org/grass/browser/grass/trunk/lib/python/temporal/temporal_granularity.py)
- [x] granularity should be extended also to other modules, for v.in.sos you should be able to save the values in the same column for the same hours

Probably the function/functions for granularity could be moved to `libsos`

**Comment by pesekon2** [comment]
Don't you know, is there any handy function to convert the granularity string in that format (2 days, 5 months) into seconds (int)? Because everything I'm able to find in the temporal is working with stds and I would like to avoid the functions duplicity.

**Comment by lucadelu** [comment]
Yes there is a function in temporal library  http://trac.osgeo.org/grass/browser/grass/trunk/lib/python/temporal/temporal_granularity.py#L1104

_Sent from my HUAWEI PRA-LX1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
