### ISSUE TITLE
-s flag to all modules

### ISSUE THREAD

**Issue by pesekon2** [pesekon2/GRASS-GIS-SOS-tools#42]
* implement -s flag also to r.in.sos

**Comment by ninsbl** [comment]
In that case the function should probably go to soslib?

**Comment by pesekon2** [comment]
The first answer was: yes.  
But then I realized: Is this flag useful also for the spatio-temporal modules? 
So maybe the only module in consideration is r.in.sos and in this one, the import will be different (raster instead of vector) --> separate functions in both modules are okay.

**Comment by pesekon2** [comment]
After a discussion, it was decided not to implement -s flags into other modules than v.in.sos and r.in.sos. Closing this ticket.
