### ISSUE TITLE
rewrite to Python 3

### ISSUE THREAD

**Issue by pesekon2** [pesekon2/GRASS-GIS-SOS-tools#44]
The default Python in GRASS GIS is now Python 3. All modules should be rewritten to work with that version of Python. 

Necessary to solve #43.

**Comment by ninsbl** [comment]
With GRASS 8 Python 2 support will be dropped. GRASS 7.6 is still based on Python 2 though.
Not sure if it is worth the effort to maintain Python 2 and thus compatibility with GRASS 7.6...

**Comment by pesekon2** [comment]
> Not sure if it is worth the effort to maintain Python 2 and thus compatibility with GRASS 7.6...

I don't think so. I would go directly for Python 3.
